### ISSUE TITLE
Is anyone still watching this?

### ISSUE THREAD

**Issue by michaeltmarion** [michaeltmarion/OOGASalad#1]
Hi all — I'm cleaning out my GitHub repository of old projects and was wondering if anyone wanted to take ownership of this project before I delete it. I'll delete it next week if no one responds to this.

@tylernisonoff @weskpga @chinnychin19 @rtoussaint @mray90 @AustinNess @rsansel

**Comment by rsansel** [comment]
I guess I'll go ahead and take it over.


On Fri, Sep 25, 2015 at 12:56 PM, Michael Marion <notifications@github.com>
wrote:

Hi all — I'm cleaning out my GitHub repository of old projects and was
wondering if anyone wanted to take ownership of this project before I
delete it. I'll delete it next week if no one responds to this.


@tylernisonoff <https://github.com/tylernisonoff> @weskpga
<https://github.com/weskpga> @chinnychin19 <https://github.com/chinnychin19>
@rtoussaint <https://github.com/rtoussaint> @mray90
<https://github.com/mray90> @AustinNess <https://github.com/AustinNess>
@rsansel <https://github.com/rsansel>


—
Reply to this email directly or view it on GitHub
<https://github.com/michaeltmarion/OOGASalad/issues/1>.










-- 
Robert S. Ansel
Lead Developer - DevilPrint
Standards & Risk Management Chair - Duke Chi Psi Fraternity
Information Technology Advisory Council - Duke University

**Comment by michaeltmarion** [comment]
You rock. Just sent you a request to transfer ownership.

How's life at Box?

**Comment by rsansel** [comment]
I absolutely love it. The people here are amazing and I'm getting to build
out some new long-term systems from scratch. Couldn't be happier! How's
LinkedIn treating you?


On Fri, Sep 25, 2015 at 13:08 PM, Michael Marion <notifications@github.com>
wrote:

You rock. Just sent you a request to transfer ownership.


How's life at Box?


—
Reply to this email directly or view it on GitHub
<https://github.com/michaeltmarion/OOGASalad/issues/1#issuecomment-143339942>
.










-- 
Robert S. Ansel
Lead Developer - DevilPrint
Standards & Risk Management Chair - Duke Chi Psi Fraternity
Information Technology Advisory Council - Duke University

**Comment by michaeltmarion** [comment]
LinkedIn's dope! The NYC office is only about 40 engineers so it runs like a startup without the worrying over [funding/resources/holy shit will the company exist a year from now]. Great people, great team, great products to build. No complaints here!

**Comment by rsansel** [comment]
Woah, I just noticed. I seriously need to update my email signature, lol

**Comment by michaeltmarion** [comment]
For sure. I'm sure I'll be visiting the California office sometime in the coming months.
